apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        echo "Cleaning up temporary files..."
        rm -rf /tmp/*
